<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Win.Design" Version="24.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MES.DATA\MES.DATA.csproj" />
    <ProjectReference Include="..\MES.PLC\MES.PLC.csproj" />
  </ItemGroup>

</Project>
